### ISSUE TITLE
Error when handling extra config file

### ISSUE THREAD

**Issue by celinakalus** [ft/makemehappy#3]
First off: Don't worry about getting to this before the holidays, this of course can wait.

I am currently observing an error when trying to use my `system.yaml` in mmh v0.27.

```log
[2024-12-18 13:33:25.906628] INFO: MakeMeHappy: Phase: zephyr/stm32h747i_disco_m7/hsem-blinky/gnuarmemb/debug: configure
Traceback (most recent call last):
  File "/home/ckalus/contrib/makemehappy/makemehappy/system.py", line 218, in configure
    cmd = c.configureZephyr(
          ^^^^^^^^^^^^^^^^^^
  File "/home/ckalus/contrib/makemehappy/makemehappy/cmake.py", line 122, in configureZephyr
    if (zephyrWithExtraConfFile(mmh.expandFile(kernel))):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ckalus/contrib/makemehappy/makemehappy/cmake.py", line 92, in zephyrWithExtraConfFile
    version = list(map(int, tag[1:].split('.')[0:3]))
                            ~~~^^^^
TypeError: 'NoneType' object is not subscriptable
```

My module.yaml:

```yaml
name: zephyr-modules
type: zephyr
install: true

# So, zephyr expects boards/ to be in the top-level of all directories inside
# of BOARD_ROOT, so we're putting . here, because there is ./boards in here.
zephyr-board-root: .

dependencies:
  - name: ufw
    revision: v5.6.0
  - name: pandoc-doc-style
    revision: v0.3.0
  - name: zephyr-kernel
    revision: v3.7.1
  - name: zephyr-arm-cmsis
    revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
  - name: zephyr-hal-stm32
    revision: f1317150eac951fdd8259337a47cbbc4c2e6d335

zephyr-aliases:
  stm32h747i_disco_m7: stm32h747i_disco/stm32h747xx/m7
  stm32h747i_disco_m4: stm32h747i_disco/stm32h747xx/m4

targets:
  - application: samples/sample-basic-blinky/
    boards:
      - stm32h747i_disco_m4
      - stm32h747i_disco_m7
      - nucleo_f767zi
      - nucleo_l476rg
      - nucleo_f302r8
    toolchains:
      - name: gnuarmemb
        path: /usr
    modules:
      - zephyr-arm-cmsis
      - zephyr-hal-stm32

buildconfigs:
  - release
  - debug

buildtools:
  - ninja
```

Maybe you can figure something out from this already. I am still in the process of debugging what is actually going on there, which is why I am kind of just infodumping here.

Happy holidays! :christmas_tree:

**Comment by ft** [comment]
Hm. I don't see the additional config file specified in the `system.yaml` you've shown.

The issue looks a little like `mmh` can't figure out the version of the `zephyr-kernel` checkout, and then runs into an issue, that was fixed in a3ca8c37a49 (which is post-0.27, but included in 0.28). Does the git clone setup in your case try to save space and maybe doesn't have the `v3.7.1` tag available? I have seen this in gitlab CI configurations in the past.

If that is not it, do you think you can supply a minimal example, for me to reproduce this (i.e. no proprietary modules, and a known application)? If you need a stand-alone zephyr application, that is publicly available, for demonstration purposes, you can use `git@gitlab.com:ft/zephyr-sample-blinky.git`.

**Comment by ft** [comment]
Sidenote: You are specifying the revisions for `zephyr-arm-cmsis` and `zephyr-hal-stm32` explicitly. You can leave those off and `mmh` will ask the `zephyr-kernel` repository if it knows an appropriate revision for these. So if you just specify the revision of the kernel, you just get all the revision recommendations for all the modules zephyr's `west.yaml` knows about¹. You may already know this and have a reason for the explicit spec, but I figure it can't hurt to mention it.

¹ The mapping of `mmh` module names to `west` names is done in [data.yaml](https://github.com/ft/makemehappy/blob/master/data/sources.yaml#L126).
